apiVersion: v1
kind: Template
metadata:
  name: route-template-${APP_NAME}
  annotations:
    description: Route template for ${APP_NAME} app on OCP
    tags: wepsphere,liberty,java,template
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    port:
      targetPort: "http-unsec"
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
    tls:
      termination: edge
parameters:
  - name: APP_NAME
    description: Application Name. To be used for the buildconfig, deploymentconfig, and pods.
