apiVersion: v1
kind: Template
metadata:
  name: dc-template-${APP_NAME}
  annotations:
    description: Deployment config template for ${APP_NAME} app on OCP
    tags: wepsphere,liberty,java,template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - ${APP_NAME}
                topologyKey: kubernetes.io/hostname
        containers:
          - image: ${IMAGE}
            imagePullPolicy: IfNotPresent
            name: ${APP_NAME}
            env:
              - name: WLP_LOGGING_CONSOLE_FORMAT
                value: json
              - name: WLP_LOGGING_CONSOLE_LOGLEVEL
                value: info
              - name: WLP_LOGGING_CONSOLE_SOURCE
                value: message,trace,accessLog,ffdc
              - name: KUBERNETES_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: IIOP_ENDPOINT_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name : KEYSTORE_REQUIRED
                value: "false"
            ports:
            - containerPort: 9080
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
            readinessProbe:
              httpGet:
                path: / 
                port: 9080
              initialDelaySeconds: 30
              periodSeconds: 5
            livenessProbe:
              httpGet:
                path: / 
                port: 9080
              initialDelaySeconds: 30
              periodSeconds: 5
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - name: cache-volume
              mountPath: /opt/ibm/wlp/output
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: 
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: cache-volume
    test: false
    triggers:
    - type: ConfigChange

parameters:
  - name: APP_NAME
    description: Application Name. To be used for the buildconfig, deploymentconfig, and pods.
  - name: IMAGE
    description: image
