apiVersion: v1
kind: Template
metadata:
  name: svc-template-${APP_NAME}
  annotations:
    description: Svc template for ${APP_NAME} app on OCP
    tags: wepsphere,liberty,java,template
objects:
- apiVersion: v1
  kind: Service 
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - name: http-unsec
      port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      name: ${APP_NAME}
parameters:
  - name: APP_NAME
    description: Application Name. To be used for the buildconfig, deploymentconfig, and pods.